### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BookOwl** [BookOwl/nustack#2]
- [x] FIX INSTALL ISSUES!!!
- [ ] Finish creating docs.
- [x] Flesh out the standard library.
- [x] Improve error handling
- [x] Add turtle graphics
- [x] Figure what else I need to do. :package:

**Comment by jeandrek** [comment]
Isn't 1. done?

**Comment by BookOwl** [comment]
Yes, I just forgot to update the list
